import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
    getCharbonsAction,
    getActionneursAction,
    getCoursesAction,
    getResourcesAction,
    authenticateAction,
} from "@lib/actions";
import CharbonsProvider from "./context/CharbonsContext";
import ActionneursProvider from "./context/ActionneursContext";
import CoursesProvider from "./context/CoursesContext";
import ResourcesProvider from "./context/ResourcesContext";
import AuthProvider from "./context/AuthContext";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const charbons = await getCharbonsAction();
    const actionneurs = await getActionneursAction();
    const courses = await getCoursesAction();
    const resources = await getResourcesAction();
    const authData = await authenticateAction();
    console.log(authData);

    return (
        <AuthProvider initialAuthData={authData}>
            <CharbonsProvider initialCharbons={charbons}>
                <ActionneursProvider initialActionneurs={actionneurs}>
                    <CoursesProvider initialCourses={courses}>
                        <ResourcesProvider initialResources={resources}>
                            <html lang="fr">
                                <body
                                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                                >
                                    {children}
                                </body>
                            </html>
                        </ResourcesProvider>
                    </CoursesProvider>
                </ActionneursProvider>
            </CharbonsProvider>
        </AuthProvider>
    );
}
