import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
    getCharbonsAction,
    getActionneursAction,
    getCoursesAction,
    getResourcesAction,
    authenticateAction,
} from "@lib/actions";
import CharbonProvider from "./context/CharbonContext";
import ActionneurProvider from "./context/ActionneurContext";
import CourseProvider from "./context/CourseContext";
import ResourceProvider from "./context/ResourceContext";
import AuthProvider from "./context/AuthContext";
import "../lib/discord";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const charbons = await getCharbonsAction();
    const actionneurs = await getActionneursAction();
    const courses = await getCoursesAction();
    const resources = await getResourcesAction();
    const authData = await authenticateAction();

    return (
        <AuthProvider initialAuthData={authData}>
            <CharbonProvider initialCharbons={charbons}>
                <ActionneurProvider initialActionneurs={actionneurs}>
                    <CourseProvider initialCourses={courses}>
                        <ResourceProvider initialResources={resources}>
                            <html lang="fr">
                                <body
                                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                                >
                                    {children}
                                </body>
                            </html>
                        </ResourceProvider>
                    </CourseProvider>
                </ActionneurProvider>
            </CharbonProvider>
        </AuthProvider>
    );
}
