import type { Metadata } from "next";
import "./globals.css";
import { Commissioner } from "next/font/google";
import { ReactNode } from "react";

const commissioner = Commissioner({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: ReactNode;
}>) => {
    return (
        <html lang="fr">
            <body className={`${commissioner.className} antialiased`}>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
